# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - api-iema

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://apiiemadev.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d4fe3731f78d4a4097a7e4c215b40c0c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bef08777c82646028797fea1fa5d1ca4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: apiiemadev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d4fe3731f78d4a4097a7e4c215b40c0c }}/api-iema:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'api-iema'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a918b4147b9b40f9b93804a8c38a4735 }}
        images: 'apiiemadev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d4fe3731f78d4a4097a7e4c215b40c0c }}/api-iema:${{ github.sha }}'